import type { PilotTemplate } from '../domain/pilot-template.js';

const TIMESTAMP = '2026-01-01T00:00:00.000Z';
const TRUST_DOMAIN_ID = 'trust-domain-datasys-agent-republic';

const BUYER_COO_PERSONA_ID = 'persona-buyer-coo-operations-director';
const BUYER_PMO_DIRECTOR_PERSONA_ID = 'persona-buyer-pmo-director';
const BUYER_DELIVERY_DIRECTOR_PERSONA_ID = 'persona-buyer-services-delivery-director';
const OPERATOR_PROJECT_MANAGER_PERSONA_ID = 'persona-operator-project-manager';
const OPERATOR_PMO_ANALYST_PERSONA_ID = 'persona-operator-pmo-analyst';
const OPERATOR_DELIVERY_MANAGER_PERSONA_ID = 'persona-operator-delivery-manager';

/**
 * Datasys Internal PM / Project Governance Pilot -- shows how AOC governs
 * autonomous project-management execution (PMFreak) end to end: recognized
 * reads, evidence-gated invoice support, approval-gated financial actions,
 * policy enforcement, and a verifiable export/audit trail. Orchestrates
 * existing runtime truth (Recognition Runtime, Authority Graph, Approval
 * Runtime, Domain Policy Pack Runtime, Evidence / Source / Citation Runtime,
 * Action Enforcement, AOC Control Plane, AOC Enterprise Demo, Verifiable
 * Export Package) -- it never invents its own decisions.
 */
export const DATASYS_PROJECT_GOVERNANCE_PILOT_TEMPLATE: PilotTemplate = {
  id: 'datasys-project-governance',
  name: 'Datasys Internal PM / Project Governance Pilot',
  description:
    'A bounded pilot showing how an autonomous project-management agent (PMFreak) can create/update tasks, prepare invoice support, request closure evidence, and read project summaries, with every action recognized, authorized, policy-checked, evidenced, enforced, and exportable for audit.',
  status: 'draft',
  industry: 'technology_services',
  primaryUseCase: 'Autonomous PM / project governance execution governed end-to-end by AOC.',
  businessPain:
    'PMO and delivery leadership cannot let an autonomous PM agent take real actions -- reading project data, preparing invoice support, requesting closure evidence, or touching anything financially adjacent -- without a governed, auditable trail proving every action was recognized, authorized, policy-checked and evidenced before it executed.',
  aocValueProposition:
    'AOC can govern autonomous PM execution so project agents can move faster without bypassing evidence, approvals or auditability -- Recognition, Authority, Approval Runtime, the Domain Policy Pack Runtime, Evidence / Source / Citation Runtime and Action Enforcement jointly decide, and the Control Plane and Verifiable Export Package prove, that every PMFreak action stayed inside its bounded authority.',
  targetBuyerPersonaIds: [BUYER_COO_PERSONA_ID, BUYER_PMO_DIRECTOR_PERSONA_ID, BUYER_DELIVERY_DIRECTOR_PERSONA_ID],
  targetOperatorPersonaIds: [OPERATOR_PROJECT_MANAGER_PERSONA_ID, OPERATOR_PMO_ANALYST_PERSONA_ID, OPERATOR_DELIVERY_MANAGER_PERSONA_ID],
  trustDomainId: TRUST_DOMAIN_ID,
  scope: {
    inScope: [
      'PMFreak reads project summaries (low-risk, recognized action)',
      'PMFreak prepares invoice support gated on invoice/PO evidence',
      'PMFreak requests closure evidence before project handoff',
      'Finance approval gate on any payment-adjacent action PMFreak triggers',
    ],
    outOfScope: [
      'Real invoicing/ERP/accounting-system integration',
      'Real customer communications or contract negotiation',
      'Any production financial transaction',
      "Legal review of Datasys' actual customer contracts",
    ],
    durationDays: 21,
    environments: 'sandbox',
    dataSensitivity: 'synthetic_only',
    legalCompleteness: 'demo_policy_model',
    assumptions: [
      'The Datasys trust domain, PMFreak agent, and reviewer actors already exist in Recognition Runtime / Authority Graph fixtures.',
      'A finance approver role is staffed for the pilot duration.',
    ],
    constraints: ['No production system access.', 'No real customer data -- synthetic project data only.'],
  },
  actors: [
    {
      id: 'datasys-actor-pmfreak',
      name: 'PMFreak Closure Agent',
      actorType: 'internal_agent',
      role: 'Autonomous PM agent',
      trustDomainId: TRUST_DOMAIN_ID,
      expectedRecognitionState: 'recognized',
    },
    {
      id: 'datasys-actor-victor',
      name: 'Victor Valverde',
      actorType: 'human',
      role: 'PMO Analyst / Operator',
      trustDomainId: TRUST_DOMAIN_ID,
      expectedRecognitionState: 'recognized',
    },
    {
      id: 'datasys-actor-finance-approver',
      name: 'Finance Approver',
      actorType: 'human',
      role: 'Finance reviewer',
      trustDomainId: TRUST_DOMAIN_ID,
      expectedRecognitionState: 'recognized',
    },
  ],
  agents: [
    {
      id: 'datasys-agent-pmfreak',
      name: 'PMFreak',
      agentType: 'pm_agent',
      ownerActorId: 'datasys-actor-pmfreak',
      trustDomainId: TRUST_DOMAIN_ID,
      allowedActions: ['read_project_summary', 'prepare_invoice_support'],
      deniedActions: ['approve_payment'],
      requiredCapabilities: ['datasys-capability-read-project-summary', 'datasys-capability-prepare-invoice-support'],
    },
  ],
  capabilities: [
    {
      id: 'datasys-capability-read-project-summary',
      name: 'Read project summary',
      description: 'Low-risk, recognized read of a project summary record.',
      action: 'read_project_summary',
      resourceScope: 'project:HMP-14665',
      riskLevel: 'low',
      requiredAuthority: false,
      requiredApproval: false,
      requiredEvidence: false,
      policyPackSensitive: true,
    },
    {
      id: 'datasys-capability-prepare-invoice-support',
      name: 'Prepare invoice support',
      description: 'Assembles invoice support material; gated on invoice and purchase-order evidence.',
      action: 'prepare_invoice_support',
      resourceScope: 'project:HMP-14665',
      riskLevel: 'medium',
      requiredAuthority: true,
      requiredApproval: false,
      requiredEvidence: true,
      policyPackSensitive: true,
    },
    {
      id: 'datasys-capability-approve-payment',
      name: 'Approve payment',
      description: 'Approves a payment; requires finance-review approval under the financial-approval-basic policy pack.',
      action: 'approve_payment',
      resourceScope: 'project:HMP-14665',
      riskLevel: 'critical',
      requiredAuthority: true,
      requiredApproval: true,
      requiredEvidence: false,
      policyPackSensitive: true,
    },
  ],
  authorityModel: {
    authorityGrantIds: ['datasys-authority-grant-pmfreak-pm-agent'],
    delegationGrantIds: ['datasys-delegation-pmfreak-from-victor'],
    authorityProofIds: [],
    requiredCapabilities: ['datasys-capability-prepare-invoice-support', 'datasys-capability-approve-payment'],
    description: 'PMFreak acts under authority delegated by Victor Valverde (PMO Analyst) through Authority Graph; every invoice-support or payment-adjacent action is checked against this delegation.',
    walkthrough: [
      'Open Authority in the Control Plane and locate the delegation grant from Victor Valverde to PMFreak.',
      'Confirm the grant scope covers project:HMP-14665 and includes prepare_invoice_support.',
    ],
  },
  approvalModel: {
    approvalRoleIds: ['datasys-approval-role-finance-reviewer'],
    approvalRequestIds: [],
    approvalDecisionIds: [],
    approvalProofIds: [],
    approvalScenarios: [
      { action: 'approve_payment', expectedApprovalBehavior: 'required', description: 'approve_payment always requires a finance_review approval before it may proceed.' },
    ],
    walkthrough: [
      'Open Approvals in the Control Plane and locate the pending/decided finance_review request for approve_payment.',
    ],
  },
  policyModel: {
    policyPackIds: ['policy-pack-procurement-basic', 'policy-pack-financial-approval-basic', 'policy-pack-data-boundary-basic'],
    policyPackVersionIds: ['policy-pack-procurement-basic-v1', 'policy-pack-financial-approval-basic-v1', 'policy-pack-data-boundary-basic-v1'],
    demoOnly: true,
    legalCompleteness: 'demo_policy_model',
    policyScenarios: [
      { action: 'read_project_summary', expectedPolicyBehavior: 'warning', description: 'Low-risk reads are allowed with a policy warning, never blocked.' },
      { action: 'prepare_invoice_support', expectedPolicyBehavior: 'requires_evidence', description: 'procurement-basic requires invoice and purchase-order evidence before invoice support may proceed.' },
      { action: 'approve_payment', expectedPolicyBehavior: 'requires_approval', description: 'financial-approval-basic requires a finance_review approval before approve_payment may proceed.' },
    ],
    walkthrough: ['Open Policy Packs in the Control Plane and confirm procurement-basic and financial-approval-basic are active and demo-only.'],
  },
  evidenceModel: {
    sourceDocumentIds: [],
    evidenceArtifactIds: [],
    evidenceRequirementIds: [],
    evidenceSatisfactionIds: [],
    evidenceProofIds: [],
    citationIds: [],
    evidenceScenarios: [
      { action: 'prepare_invoice_support', requiredEvidenceTypes: ['invoice', 'purchase_order'], expectedEvidenceBehavior: 'satisfied', description: 'Invoice and purchase-order evidence must be submitted and accepted before invoice support proceeds.' },
      { action: 'approve_payment', requiredEvidenceTypes: ['approval_memo'], expectedEvidenceBehavior: 'satisfied', description: "An approval memo documents the finance reviewer's decision." },
    ],
    walkthrough: ['Open Evidence in the Control Plane (or the Evidence Runtime fixture) and confirm invoice/PO evidence is accepted and cited against the policy decision.'],
  },
  actions: [
    {
      id: 'datasys-action-read-project-summary',
      name: 'Read project summary',
      description: 'PMFreak reads the HMP-14665 project summary.',
      actorId: 'datasys-actor-pmfreak',
      agentId: 'datasys-agent-pmfreak',
      action: 'read_project_summary',
      capability: 'datasys-capability-read-project-summary',
      resourceScope: 'project:HMP-14665',
      riskLevel: 'low',
      expectedRecognition: 'allowed',
      expectedAuthority: 'not_required',
      expectedApproval: 'not_required',
      expectedPolicy: 'warning',
      expectedEvidence: 'not_required',
      expectedEnforcement: 'execute_allowed',
      expectedExecution: 'executed',
    },
    {
      id: 'datasys-action-prepare-invoice-support',
      name: 'Prepare invoice support',
      description: 'PMFreak prepares invoice support material for INV-1001.',
      actorId: 'datasys-actor-pmfreak',
      agentId: 'datasys-agent-pmfreak',
      action: 'prepare_invoice_support',
      capability: 'datasys-capability-prepare-invoice-support',
      resourceScope: 'project:HMP-14665',
      riskLevel: 'medium',
      expectedRecognition: 'requires_evidence',
      expectedAuthority: 'valid',
      expectedApproval: 'not_required',
      expectedPolicy: 'requires_evidence',
      expectedEvidence: 'missing',
      expectedEnforcement: 'evidence_required',
      expectedExecution: 'not_executed',
    },
    {
      id: 'datasys-action-approve-payment',
      name: 'Approve payment',
      description: "A payment tied to PMFreak's project requires finance approval before it can proceed.",
      actorId: 'datasys-actor-finance-approver',
      action: 'approve_payment',
      capability: 'datasys-capability-approve-payment',
      resourceScope: 'project:HMP-14665',
      riskLevel: 'critical',
      expectedRecognition: 'allowed',
      expectedAuthority: 'valid',
      expectedApproval: 'required',
      expectedPolicy: 'requires_approval',
      expectedEvidence: 'not_required',
      expectedEnforcement: 'approval_required',
      expectedExecution: 'not_executed',
    },
  ],
  scenarios: [
    {
      id: 'datasys-scenario-low-risk-read',
      name: 'PMFreak reads a project summary (allowed with policy warning)',
      description: 'A low-risk read is recognized, policy-warned but allowed, and executed.',
      demoScenarioId: 'policy-pack-low-risk-read-warning-allowed',
      actionIds: ['datasys-action-read-project-summary'],
      expectedOutcome: 'warning_allowed',
      controlPlaneFocus: 'enforcement',
      exportPackageType: 'decision_packet',
      buyerMessage: 'Even routine reads flow through the same governed pipeline -- nothing PMFreak does is invisible.',
      operatorMessage: 'Open Enforcement to see the execute_allowed decision, and Policy Packs to see the warning-level rule that matched.',
      technicalMessage: 'AocGuard.enforce() returns execute_allowed with a policy warning reason code; the executor runs.',
      acceptanceCriterionIds: ['datasys-acceptance-scenarios-pass'],
      successMetricIds: ['datasys-metric-operator-visibility'],
    },
    {
      id: 'datasys-scenario-invoice-support-requires-evidence',
      name: 'PMFreak invoice support is blocked pending evidence',
      description: 'prepare_invoice_support is blocked until invoice/PO evidence is attached.',
      demoScenarioId: 'policy-pack-invoice-evidence-required',
      actionIds: ['datasys-action-prepare-invoice-support'],
      expectedOutcome: 'evidence_required',
      controlPlaneFocus: 'evidence',
      exportPackageType: 'evidence_packet',
      buyerMessage: 'PMFreak cannot prepare invoice support out of thin air -- AOC requires real invoice and purchase-order evidence first.',
      operatorMessage: 'Open Evidence to see the open invoice/PO requirements, then Enforcement to see the evidence_required block.',
      technicalMessage: 'Domain Policy Pack Runtime returns requires_evidence; Action Enforcement blocks with evidence_required; Evidence Runtime tracks the open requirement.',
      acceptanceCriterionIds: ['datasys-acceptance-scenarios-pass'],
      successMetricIds: ['datasys-metric-evidence-readiness'],
    },
    {
      id: 'datasys-scenario-payment-requires-finance-approval',
      name: 'Payment approval is blocked pending finance review',
      description: 'approve_payment is blocked until a finance_review approval exists.',
      demoScenarioId: 'policy-pack-payment-approval-required',
      actionIds: ['datasys-action-approve-payment'],
      expectedOutcome: 'approval_required',
      controlPlaneFocus: 'approvals',
      exportPackageType: 'approval_decision_packet',
      buyerMessage: 'No autonomous agent approves a payment on its own -- a human finance reviewer must approve it first.',
      operatorMessage: 'Open Approvals to see the pending finance_review request, then Enforcement to see the blocked decision referencing it.',
      technicalMessage: 'financial-approval-basic requires a finance_review approval; Action Enforcement returns approval_required and the executor never runs.',
      acceptanceCriterionIds: ['datasys-acceptance-scenarios-pass', 'datasys-acceptance-export-verified'],
      successMetricIds: ['datasys-metric-risk-reduction', 'datasys-metric-policy-enforcement'],
    },
    {
      id: 'datasys-scenario-governance-walkthrough-and-export',
      name: 'Full governance walkthrough and verifiable export',
      description: 'An operator walks the Control Plane end to end and exports a verifiable decision packet.',
      demoScenarioId: 'policy-pack-control-plane-walkthrough',
      actionIds: ['datasys-action-approve-payment'],
      expectedOutcome: 'executed',
      controlPlaneFocus: 'export_packages',
      exportPackageType: 'enterprise_demo_packet',
      buyerMessage: 'Every decision PMFreak (or a human reviewer) makes can be exported as a verifiable, hash-chained packet for audit.',
      operatorMessage: 'Open Export Packages / Proofs and Audit to see the packet manifest, hash, and verification status.',
      technicalMessage: 'ExportPackageRuntime seals and verifies a decision packet referencing recognition/authority/approval/policy/enforcement proofs.',
      acceptanceCriterionIds: ['datasys-acceptance-export-verified'],
      successMetricIds: ['datasys-metric-auditability'],
    },
  ],
  controlPlaneWalkthrough: {
    id: 'datasys-control-plane-walkthrough',
    sections: [
      {
        section: 'overview',
        title: 'Overview',
        whatToShow: ['Overall decision/health summary for the Datasys trust domain.'],
        whyItMatters: 'Gives the buyer a single glance at how many actions were governed and how many required intervention.',
        expectedRowsOrReferences: ['Overview status cards'],
      },
      {
        section: 'enforcement',
        title: 'Enforcement',
        whatToShow: ['The execute_allowed, evidence_required and approval_required enforcement decisions produced by the pilot scenarios.'],
        whyItMatters: 'Proves execution was actually blocked/allowed by real Action Enforcement decisions, not a demo trick.',
        expectedRowsOrReferences: ['Enforcement decision rows for read_project_summary, prepare_invoice_support, approve_payment'],
      },
      {
        section: 'policy_packs',
        title: 'Policy Packs',
        whatToShow: ['procurement-basic and financial-approval-basic rules and the decisions they produced.'],
        whyItMatters: 'Shows the enterprise policy layer independent of recognition/authority.',
        expectedRowsOrReferences: ['Matched rule ids for the invoice-evidence and finance-review requirements'],
      },
      {
        section: 'evidence',
        title: 'Evidence',
        whatToShow: ['Open and satisfied evidence requirements for invoice/purchase-order evidence.'],
        whyItMatters: 'Proves invoice support genuinely required, and eventually received, real evidence.',
        expectedRowsOrReferences: ['Evidence requirement + satisfaction rows for prepare_invoice_support'],
      },
      {
        section: 'proofs_audit',
        title: 'Proofs / Audit',
        whatToShow: ['The proof chain linking recognition, authority, policy and enforcement decisions.'],
        whyItMatters: 'An auditor can walk this chain without trusting the UI.',
        expectedRowsOrReferences: ['Proof chain entries referencing the enforcement/policy decision ids'],
      },
      {
        section: 'export_packages',
        title: 'Export Packages',
        whatToShow: ['The sealed, verified decision packet for the finance-approval scenario.'],
        whyItMatters: 'Gives the buyer a portable, hash-verifiable artifact to take to their own auditors.',
        expectedRowsOrReferences: ['Decision packet manifest + verification status = verified'],
      },
    ],
    operatorScript: [
      'Start on Overview to set context, then open Enforcement to show the three governed actions.',
      'Open Policy Packs to show the matched rules, then Evidence to show the open/satisfied requirements.',
      'Close on Proofs / Audit and Export Packages to show the exportable, verifiable trail.',
    ],
  },
  exportPackages: [
    {
      id: 'datasys-export-invoice-evidence-packet',
      name: 'Invoice evidence packet',
      packageType: 'evidence_packet',
      targetType: 'enforcement_decision',
      targetId: 'datasys-action-prepare-invoice-support',
      expectedSections: ['summary', 'evidence', 'enforcement'],
      expectedVerificationStatus: 'verified_with_warnings',
      buyerPurpose: 'Shows an auditor exactly which evidence was required, and its current status, before invoice support could proceed.',
    },
    {
      id: 'datasys-export-payment-approval-packet',
      name: 'Payment approval decision packet',
      packageType: 'approval_decision_packet',
      targetType: 'enforcement_decision',
      targetId: 'datasys-action-approve-payment',
      expectedSections: ['summary', 'approval', 'policy', 'enforcement'],
      expectedVerificationStatus: 'verified_with_warnings',
      buyerPurpose: 'Gives finance leadership a hash-verifiable record that approve_payment was blocked pending approval.',
    },
  ],
  acceptanceCriteria: [
    {
      id: 'datasys-acceptance-scenarios-pass',
      title: 'All pilot scenarios run against real AOC runtimes and match expected outcomes',
      description: "Every declared pilot scenario binds to a real Enterprise Demo scenario and its runtime outcome matches the pilot's expected outcome.",
      type: 'runtime',
      required: true,
      verificationMethod: 'automated_test',
      expectedResult: 'Every scenario binding reports bound: true.',
    },
    {
      id: 'datasys-acceptance-export-verified',
      title: 'Decision/approval export packets verify successfully',
      description: 'The finance-approval and invoice-evidence export package definitions bind to real, verified Verifiable Export Package output.',
      type: 'export_package',
      required: true,
      verificationMethod: 'export_package_verification',
      expectedResult: 'Bound export packages report verification status verified or verified_with_warnings.',
    },
    {
      id: 'datasys-acceptance-operator-walkthrough',
      title: 'Operator can complete the Control Plane walkthrough',
      description: 'A PMO analyst can walk Enforcement, Policy Packs, Evidence, Proofs/Audit and Export Packages without confusion.',
      type: 'operator',
      required: true,
      verificationMethod: 'operator_review',
      expectedResult: 'Operator confirms every walkthrough section is clear and backed by real data.',
    },
    {
      id: 'datasys-acceptance-customer-signoff',
      title: 'Datasys stakeholder signs off on pilot scope and outcomes',
      description: 'A Datasys buyer persona confirms the pilot demonstrated the value proposition within its stated non-goals.',
      type: 'buyer',
      required: false,
      verificationMethod: 'customer_signoff',
      expectedResult: 'Signed pilot acceptance record from a Datasys stakeholder.',
    },
  ],
  successMetrics: [
    { id: 'datasys-metric-risk-reduction', label: 'Ungoverned financial actions prevented', description: 'Number of payment-adjacent actions blocked pending approval.', category: 'risk_reduction', targetValue: '100% of approve_payment attempts blocked until finance_review approval exists', measurementMethod: 'Count of approval_required enforcement decisions vs. total approve_payment attempts.' },
    { id: 'datasys-metric-auditability', label: 'Exportable, verified decision packets', description: 'Share of governed actions with a verified export packet.', category: 'auditability', targetValue: 'Every finance-approval-adjacent decision has a verified export packet', measurementMethod: 'Count of verified export packages vs. total scenarios requiring one.' },
    { id: 'datasys-metric-operator-visibility', label: 'Operator walkthrough completeness', description: 'Control Plane sections an operator can inspect for this pilot.', category: 'operator_visibility', targetValue: 'All 6 walkthrough sections backed by real Control Plane rows', measurementMethod: 'Control Plane section availability check.' },
    { id: 'datasys-metric-policy-enforcement', label: 'Policy-pack-gated actions enforced', description: 'Share of policy-flagged actions actually blocked/warned by Action Enforcement.', category: 'policy_enforcement', targetValue: '100% of policy-flagged actions reflected in the enforcement decision', measurementMethod: 'Cross-check policyDecisionId on enforcement decisions.' },
    { id: 'datasys-metric-evidence-readiness', label: 'Evidence requirement resolution', description: 'Share of evidence requirements eventually satisfied with accepted evidence.', category: 'evidence_readiness', targetValue: 'Invoice/PO evidence requirements satisfied before invoice support proceeds', measurementMethod: 'Evidence Runtime requirement/satisfaction status check.' },
    { id: 'datasys-metric-buyer-confidence', label: 'Buyer confidence in autonomous PM execution', description: 'Qualitative buyer confidence after the pilot.', category: 'buyer_confidence', targetValue: 'Buyer persona affirms AOC prevented at least one ungoverned action', measurementMethod: 'Buyer walkthrough sign-off.' },
  ],
  risks: [
    { id: 'datasys-risk-demo-only-confusion', title: 'Demo-only policy packs mistaken for production policy', description: "Stakeholders might assume procurement-basic/financial-approval-basic reflect Datasys' actual finance policy.", severity: 'medium', mitigation: 'Every artifact and walkthrough explicitly labels the policy packs demo-only and non-production.', ownerPersonaId: BUYER_PMO_DIRECTOR_PERSONA_ID },
    { id: 'datasys-risk-scope-creep', title: 'Pilot scope expands into real ERP/invoicing integration', description: 'Stakeholders may ask to connect PMFreak to a real invoicing system mid-pilot.', severity: 'medium', mitigation: 'Scope document explicitly lists real ERP integration as out of scope; any request routes to a follow-on engagement.', ownerPersonaId: BUYER_DELIVERY_DIRECTOR_PERSONA_ID },
  ],
  script: {
    id: 'datasys-pilot-script',
    executiveTalkTrack: [
      'PMFreak already reads, prepares, and requests -- the question is whether it can be trusted with autonomy. AOC is how you get a yes.',
    ],
    operatorTalkTrack: [
      'Watch PMFreak attempt three real actions: a low-risk read, invoice support, and a payment approval.',
      'Each one is decided by real Recognition, Authority, Policy Pack and Enforcement runtimes -- nothing here is scripted output.',
    ],
    technicalTalkTrack: [
      'Every decision carries a policyDecisionId/policyProofId and an enforcement decision id you can trace in Proofs / Audit.',
      'The export packet at the end is a hash-chained, independently verifiable artifact -- not a screenshot.',
    ],
    buyerTalkTrack: ['This is what governed autonomy looks like: PMFreak moves faster on the reads it is allowed to do, and stops cleanly on the ones it is not.'],
    demoFlow: [
      { step: 1, title: 'Low-risk read', instruction: 'Run the low-risk-read-warning-allowed scenario.', expectedObservation: 'Execution allowed with a policy warning.' },
      { step: 2, title: 'Invoice support blocked', instruction: 'Run the invoice-evidence-required scenario.', expectedObservation: 'Execution blocked pending invoice/PO evidence.' },
      { step: 3, title: 'Payment approval blocked', instruction: 'Run the payment-approval-required scenario.', expectedObservation: 'Execution blocked pending finance_review approval.' },
      { step: 4, title: 'Control Plane + export', instruction: 'Walk the Control Plane and export a verified decision packet.', expectedObservation: 'Verified export package with matching proof references.' },
    ],
    closingStatement: 'AOC does not slow PMFreak down -- it draws the exact line between what it can do alone and what it cannot, and proves it.',
    legalDisclaimer: 'This demo script uses demo-only policy packs and synthetic data. It is not legal advice and does not prove production compliance.',
  },
  nonGoals: [
    'This pilot does not implement a standalone SaaS product, billing, or multi-tenant infrastructure.',
    'This pilot does not integrate with a real ERP/invoicing system.',
    'This pilot does not constitute legal advice or prove regulatory/production compliance.',
  ],
  legalDisclaimer:
    'This pilot template uses demo-only policy packs (procurement-basic, financial-approval-basic, data-boundary-basic) and synthetic project data. It is not legal advice, does not prove production compliance, and evidence presence does not prove legal sufficiency unless explicitly marked verified_by_customer or verified_by_counsel.',
  createdAt: TIMESTAMP,
  updatedAt: TIMESTAMP,
};
