export const BILLING_ERROR_CODES = {
  BILLING_STATE_INVALID: 'BILLING_STATE_INVALID',
  BILLING_PLAN_RESOLUTION_FAILED: 'BILLING_PLAN_RESOLUTION_FAILED',
  BILLING_QUOTA_EXCEEDED: 'BILLING_QUOTA_EXCEEDED',
  BILLING_FEATURE_NOT_ENTITLED: 'BILLING_FEATURE_NOT_ENTITLED',
  BILLING_PAYMENT_REQUIRED: 'BILLING_PAYMENT_REQUIRED',
  BILLING_SUBSCRIPTION_EXPIRED: 'BILLING_SUBSCRIPTION_EXPIRED',
  BILLING_ENFORCEMENT_ERROR: 'BILLING_ENFORCEMENT_ERROR',
} as const;

export type BillingErrorCode = typeof BILLING_ERROR_CODES[keyof typeof BILLING_ERROR_CODES];
