export const GOVERNANCE_ERROR_CODES = {
  GOVERNANCE_POLICY_EVALUATION_FAILED: 'GOVERNANCE_POLICY_EVALUATION_FAILED',
  GOVERNANCE_TREATY_CONFLICT: 'GOVERNANCE_TREATY_CONFLICT',
  GOVERNANCE_OBLIGATION_UNRESOLVABLE: 'GOVERNANCE_OBLIGATION_UNRESOLVABLE',
  GOVERNANCE_ESCALATION_FAILED: 'GOVERNANCE_ESCALATION_FAILED',
  GOVERNANCE_AUDIT_DELIVERY_FAILED: 'GOVERNANCE_AUDIT_DELIVERY_FAILED',
  GOVERNANCE_SCOPE_RESOLUTION_FAILED: 'GOVERNANCE_SCOPE_RESOLUTION_FAILED',
  GOVERNANCE_IDENTITY_RESOLUTION_FAILED: 'GOVERNANCE_IDENTITY_RESOLUTION_FAILED',
} as const;

export type GovernanceErrorCode = typeof GOVERNANCE_ERROR_CODES[keyof typeof GOVERNANCE_ERROR_CODES];
