export const RUNTIME_ERROR_CODES = {
  RUNTIME_INTERNAL_ERROR: 'RUNTIME_INTERNAL_ERROR',
  RUNTIME_CONFIGURATION_INVALID: 'RUNTIME_CONFIGURATION_INVALID',
  RUNTIME_PORT_UNAVAILABLE: 'RUNTIME_PORT_UNAVAILABLE',
  RUNTIME_VERSION_INCOMPATIBLE: 'RUNTIME_VERSION_INCOMPATIBLE',
  RUNTIME_ASSERTION_FAILED: 'RUNTIME_ASSERTION_FAILED',
  RUNTIME_DESERIALIZATION_ERROR: 'RUNTIME_DESERIALIZATION_ERROR',
  RUNTIME_SERIALIZATION_ERROR: 'RUNTIME_SERIALIZATION_ERROR',
  RUNTIME_STATE_INVALID: 'RUNTIME_STATE_INVALID',
} as const;

export type RuntimeErrorCode = typeof RUNTIME_ERROR_CODES[keyof typeof RUNTIME_ERROR_CODES];
