import type { PMFreakAgentAction } from './pmfreak-agent-passport-types.js';

/**
 * PMFreak action catalog. Every action names the capability it draws on and
 * the evidence/approval it requires. A passport granting the underlying
 * capability never bypasses these -- see `resolvePMFreakAgentPassportAction`.
 */
export const PMFREAK_ACTIONS: readonly PMFreakAgentAction[] = [
  {
    actionId: 'pmfreak.action.schedule.detect_variance',
    capabilityId: 'pmfreak.capability.schedule.detect_variance',
    title: 'Detect schedule variance',
    description: 'Detect deviation between the current project status and its schedule baseline.',
    category: 'schedule',
    sensitivity: 'low',
    requiresEvidenceIds: ['pmfreak.evidence.project_status_source', 'pmfreak.evidence.schedule_baseline'],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.schedule.propose_change',
    capabilityId: 'pmfreak.capability.schedule.propose_change',
    title: 'Propose schedule change',
    description: 'Draft a proposed schedule change or replanning recommendation.',
    category: 'schedule',
    sensitivity: 'medium',
    requiresEvidenceIds: ['pmfreak.evidence.schedule_baseline', 'pmfreak.evidence.dependency_record'],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.schedule.apply_change',
    capabilityId: 'pmfreak.capability.schedule.apply_change',
    title: 'Apply schedule change',
    description: 'Apply a schedule change, including a contractual date change, to a project.',
    category: 'schedule',
    sensitivity: 'high',
    requiresEvidenceIds: ['pmfreak.evidence.schedule_baseline'],
    requiresApprovalIds: ['pmfreak.approval.pm_approval'],
    restrictedByDefault: true,
  },
  {
    actionId: 'pmfreak.action.risk.create_draft',
    capabilityId: 'pmfreak.capability.risk.create_draft',
    title: 'Create risk draft',
    description: 'Create a draft project risk record and recommend mitigation.',
    category: 'risk',
    sensitivity: 'low',
    requiresEvidenceIds: [],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.risk.close',
    capabilityId: 'pmfreak.capability.risk.close',
    title: 'Close risk',
    description: 'Close an open project risk record.',
    category: 'risk',
    sensitivity: 'high',
    requiresEvidenceIds: ['pmfreak.evidence.risk_record'],
    requiresApprovalIds: ['pmfreak.approval.pm_approval'],
    restrictedByDefault: true,
  },
  {
    actionId: 'pmfreak.action.evidence.request',
    capabilityId: 'pmfreak.capability.evidence.request',
    title: 'Request evidence',
    description: 'Request project evidence from a source.',
    category: 'evidence',
    sensitivity: 'low',
    requiresEvidenceIds: [],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.evidence.classify',
    capabilityId: 'pmfreak.capability.evidence.classify',
    title: 'Classify evidence',
    description: 'Classify collected project evidence by type and completeness.',
    category: 'evidence',
    sensitivity: 'low',
    requiresEvidenceIds: [],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.evidence.prepare_bundle',
    capabilityId: 'pmfreak.capability.evidence.prepare_bundle',
    title: 'Prepare evidence bundle',
    description: 'Prepare a bundle of collected project evidence for review.',
    category: 'evidence',
    sensitivity: 'medium',
    requiresEvidenceIds: ['pmfreak.evidence.deliverable_evidence'],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.communication.draft_client_update',
    capabilityId: 'pmfreak.capability.communication.draft_client_update',
    title: 'Draft client update',
    description: 'Draft a client-facing communication, status update, or meeting minutes.',
    category: 'communication',
    sensitivity: 'low',
    requiresEvidenceIds: [],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.communication.send_client_update',
    capabilityId: 'pmfreak.capability.communication.send_client_update',
    title: 'Send client update',
    description: 'Send a drafted client-facing communication externally.',
    category: 'communication',
    sensitivity: 'high',
    requiresEvidenceIds: ['pmfreak.evidence.client_communication_draft'],
    requiresApprovalIds: ['pmfreak.approval.pm_approval'],
    restrictedByDefault: true,
  },
  {
    actionId: 'pmfreak.action.billing.check_readiness',
    capabilityId: 'pmfreak.capability.billing.check_readiness',
    title: 'Check billing readiness',
    description: 'Evaluate whether a milestone appears ready for billing based on evidence, approvals, and acceptance signals.',
    category: 'billing',
    sensitivity: 'medium',
    requiresEvidenceIds: ['pmfreak.evidence.billing_milestone_record', 'pmfreak.evidence.deliverable_evidence'],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.billing.mark_ready',
    capabilityId: 'pmfreak.capability.billing.mark_ready',
    title: 'Mark milestone billing-ready',
    description: 'Mark a milestone as ready for billing within AOC Enterprise. This does not create an invoice, send an invoice, or release payment, and does not certify customer acceptance.',
    category: 'billing',
    sensitivity: 'critical',
    requiresEvidenceIds: ['pmfreak.evidence.deliverable_evidence', 'pmfreak.evidence.customer_acceptance_record'],
    requiresApprovalIds: ['pmfreak.approval.pm_approval', 'pmfreak.approval.billing_review'],
    restrictedByDefault: true,
  },
  {
    actionId: 'pmfreak.action.change_control.classify_request',
    capabilityId: 'pmfreak.capability.change_control.classify_request',
    title: 'Classify change request',
    description: 'Classify and route an incoming project change request.',
    category: 'change_control',
    sensitivity: 'low',
    requiresEvidenceIds: ['pmfreak.evidence.change_request_record'],
    requiresApprovalIds: [],
    restrictedByDefault: false,
  },
  {
    actionId: 'pmfreak.action.change_control.approve_request',
    capabilityId: 'pmfreak.capability.change_control.approve_request',
    title: 'Approve change request',
    description: 'Approve a project change request.',
    category: 'change_control',
    sensitivity: 'high',
    requiresEvidenceIds: ['pmfreak.evidence.change_request_record'],
    requiresApprovalIds: ['pmfreak.approval.pm_approval'],
    restrictedByDefault: true,
  },
];

export function findPMFreakAction(actionId: string): PMFreakAgentAction | undefined {
  return PMFREAK_ACTIONS.find((action) => action.actionId === actionId);
}
