import type { RuntimePersistenceEnvelope } from '../persistence';
export const RUNTIME_VAULT_BOUNDARY_VERSION = 1 as const;
export const RUNTIME_VAULT_ATTESTATION_VERSION = 1 as const;
export type RuntimeVaultSovereignScope = 'local' | 'enterprise' | 'hybrid' | 'federated-ready';
export interface RuntimeVaultIdentity { vaultId: string; vaultOwnerId: string; tenantId: string; workspaceId: string; trustDomain: string; runtimeId: string; continuityLineageId: string; sovereignScope: RuntimeVaultSovereignScope; federationCompatibilityVersion: string; }
export interface RuntimeVaultMetadata { boundaryVersion: number; createdAt: string; updatedAt: string; portability: { byosCompatible: true; storageAgnostic: true; supportsSovereignExport: true; supportsSovereignImport: true; }; }
export interface RuntimeVaultAttestation { attestedAt: string; attestationVersion: number; continuityFingerprint: string; replayLineageFingerprint: string; lifecycleIntegrityFingerprint: string; restorationFingerprint: string; }
export interface RuntimeVaultBoundary { boundaryType: 'aoc.runtime.vault.boundary'; identity: RuntimeVaultIdentity; metadata: RuntimeVaultMetadata; continuity: { continuityEpoch: number; continuityVersion: number; operationalSequenceNumber: number; replayLineageId: string; restorationLineageId: string; }; envelope: RuntimePersistenceEnvelope; attestation: RuntimeVaultAttestation; }
export interface RuntimeVaultIsolationContext { tenantId: string; workspaceId: string; runtimeId: string; trustDomain: string; vaultOwnerId: string; expectedContinuityLineageId?: string; minimumContinuityVersion?: number; }
export interface RuntimeVaultHydrationContext extends RuntimeVaultIsolationContext { requireMonotonicContinuity?: boolean; }
export interface RuntimeVaultContinuityContext { expectedContinuityEpoch?: number; expectedRuntimeSessionId?: string; minimumOperationalSequenceNumber?: number; }
export interface RuntimeVaultValidationReport { valid: boolean; errors: string[]; warnings: string[]; }
export interface RuntimeVaultAdapter { persistVaultEnvelope(boundary: RuntimeVaultBoundary): Promise<{ persisted: boolean; vaultId: string }>; hydrateVaultEnvelope(identity: RuntimeVaultIdentity): Promise<RuntimeVaultBoundary | undefined>; validateVaultBoundary(boundary: RuntimeVaultBoundary): Promise<RuntimeVaultValidationReport>; attestVaultIntegrity(boundary: RuntimeVaultBoundary): Promise<RuntimeVaultAttestation>; exportVaultEnvelope(boundary: RuntimeVaultBoundary): Promise<string>; importVaultEnvelope(serializedBoundary: string): Promise<RuntimeVaultBoundary>; }
export interface RuntimeVaultManager { createVaultBoundary(input: { envelope: RuntimePersistenceEnvelope; tenantId: string; workspaceId: string; vaultOwnerId: string; sovereignScope?: RuntimeVaultSovereignScope; federationCompatibilityVersion?: string; now?: string; }): RuntimeVaultBoundary; validateVaultBoundary(boundary: RuntimeVaultBoundary, isolation: RuntimeVaultIsolationContext, continuity?: RuntimeVaultContinuityContext): RuntimeVaultValidationReport; hydrateVaultBoundary(boundary: RuntimeVaultBoundary, context: RuntimeVaultHydrationContext): RuntimePersistenceEnvelope; exportVaultBoundary(boundary: RuntimeVaultBoundary): string; importVaultBoundary(serializedBoundary: string): RuntimeVaultBoundary; attestVaultBoundary(boundary: RuntimeVaultBoundary, now?: string): RuntimeVaultAttestation; }
